<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cbam_annuairecbam"
 *
 * Auto generated by Extension Builder 2017-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'annuaireCBAM',
	'description' => 'Mathieu Amyot
Cecile Ballini',
	'category' => 'plugin',
	'author' => 'Mathieu, Cécile Ballini',
	'author_email' => 'mathieu.amyot@etu.u-bordeaux.fr, cecile.ballini@etu.u-bordeaux.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);